### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by AxelTerizaki** [j-holub/Node-MPV#73] opened 2020-03-23 22:24 UTC
We talked about this a long time ago, and I had volunteered to help a bit with this particular issue, if you'd like.

I did look into it many months ago, and my main issue was that this would involve a more or less complete rewrite of the code to be typescript and modern JS-compliant. 

It oculd take some time, but I do happen to have some free time now that we reached a big milestone with Karaoke Mugen (now powered by Electron)

If you're still interested, I can start working on it, but it'll be a all-or-nothing approach : as we can't just have parts in typescript and other parts in plain JS.

If you'd like to talk more about this via Discord, add AxelTerizaki#0001 there.

**Comment by j-holub** [comment] 2020-03-25 13:41
Hmm I usually like type strict coding, but in the case of TypeScript I found to make everything just so much more work and so much more hassle for a not that big benefit. I'm not sure if I'd like the idea to have the entire package written in TypeScript...

Is it possible to offer TypeScript bindings without writing the complete package in TypeScript?

**Comment by AxelTerizaki** [comment] 2020-03-25 13:48
Technically yes, you can, an example from one of my modules : https://lab.shelter.moe/axelterizaki/toyunda2ass/-/blob/master/src/types.d.ts

You just need to creates a types.d.ts file somewhere in the module.

As for your first remark, I don't think I agree. The major benefit from typescript in the module is that it allows bug-free development. VSCode can check in real-time if what you're writing is properly typed, so it's a real help to avoid some basic mistakes.

In the end it's your call of course :)

I think the module could also benefit from being rewritten using async/await instead of the good old .then promise way, to improve readability, but it's not related to typescript. I could open another issue if you'd like.

**Comment by j-holub** [comment] 2020-03-25 16:41
As said I do like type strong programming language and I agree on the benefits of them, like avoiding bug and stuff. The problem is, that TypeScript is built on top of JavaScript, and then you have to find out what type this is, and what type that is, because you need a type definition file for everything. And sometimes, there is no type for it so you end up using `any`, which is quite frankly the same as not using TypeScript in the first place.
 
> I think the module could also benefit from being rewritten using async/await instead of the good old .then promise way, to improve readability, but it's not related to typescript. I could open another issue if you'd like.

Yep I had that planned anyway, all the Promise code is so super annoying. I wasn't just sure when to do it, because at the moment there are still some features to be implemented or bugs to be fixed and I kinda didn't wanna do it in between. But that's definitely something we should do.

I think adding a `types.d.ts` file is a good first step, so at least people that prefer using TypeScript can use the module with TypeScript, whether it's written in TypeScript internally or not.

**Comment by AxelTerizaki** [comment] 2020-03-25 17:43
Hmmm, I don't quite follow the issue you have. In Karaoke Mugen for example we rarely use `any`or in very special cases. It takes some time at first, but defining all types and interfaces wasn't that much of a hassle. Plus there are types for many packages already, including node's internal modules, What might be problematic for node-mpv is to define all types from what mpv sends to the module. This could be a hindrance at first but well worth the effort (unless mpv decides to suddenly chagne stuff for some obscure reason.)

**Comment by j-holub** [comment] 2020-03-26 19:35
I issue is, that in my experience TypeScript introduced much more hassle than it did any good. It's not like C++ or Java, where everything has a type be design, but you constantly run into stuff that does not have a defined type and it slows everything down so much.
I have never run into issues that could have been prevented if I used TypeScript, it won't solve anything, it will just add another layer of possible problems.

I'm just worried, that after we made the switch to TypeScript the package is much harder to maintain and I kinda don't want to lose the ability to maintain my own project because everything is TypeScript, which in my experience just causes more problems.

How would the packaging process to upload something to NPM look like?

MPV pretty much sends only JSON, so not much work creating a type there, it's a JSON object of the same form every time. It should be

```
{
    data: any,
    request_id: number,
    error: string 
}
```

And the error string is not very informative, if you send a non existing file to mpv that should be loaded it will still return `error: success`. And `data` can be pretty much anything, string, number, I think even JSON object.

We could try rewriting the code in a seperate branch and see if that does any good, but I'm really sceptical it will.

**Comment by AxelTerizaki** [comment] 2020-03-26 19:47
It is ultimately up to you, if you don't want to I won't push the issue fruther :)

As for npm, it's pretty easy, y ou can add an extra step automatically before using npm publish, which will transpile everything into usable JS.

**Comment by j-holub** [comment] 2020-03-26 19:50
I'm willing to give it a try actually, maybe this time TypeScript is awesome? As said, actually I like languages with strong typing, I think just don't think TypeScript did a good job. But I willing to let you convice me otherwise :) 



> As for npm, it's pretty easy, y ou can add an extra step automatically before using npm publish, which will transpile everything into usable JS.

But won't that still include the TypeScript code into the package?

**Comment by AxelTerizaki** [comment] 2020-03-26 19:59
You usually add the "src" folder where your typescript resides in .npmignore and that's it :p (excluding the types which you of course include)

**Comment by AxelTerizaki** [comment] 2020-03-26 20:06
Note though that I'm no typescript expert, and the way I see is probably not the state of the art way to deal with it, but in my experience, it allows for easier modifications and avoids some common errors. We caught some bugs we didn't see in Karaoke Mugen during the shift to typescript that way. 

If you'reup for it I can start a branch on my fork after rebasing from the latest Node-MPV-2 branch here.

**Comment by AxelTerizaki** [comment] 2020-03-27 14:04
lol I just noticed you started rewriting stuff.

I began a branch this morning with typescript, and started rewriting a little. It's far from cplmplete yet, as I'm running into a few issues.

https://github.com/AxelTerizaki/Node-MPV/tree/typescript

- I wanted to rewrite everything with ES Modules instead of common JS modules and use a class but I'm not sure of how to "import" all functions from the different submodules into the main class without doing something really dirty. I'm going to ask a friend about it.
- I rewrited the load() in async as well haha, tell me what you think
- In comments I put a `Axel:` keyword when I had questions for you. For instance there is a mention of a `message` variable at some point which does not appear anywhere in ipcInterface, for some reason.
- I have started writing types for basic arguments like mpvOptions and node-mpv's options as well, I'll do the functions once I've got everything under control.

Thanks for rewriting some stuff with async/await already. Won't be too hard to merge your work. If you think I'm doing it the wrong way tell me and I'll discard the branch on my side. :)

**Comment by j-holub** [comment] 2020-03-27 14:23
Hey,

yeah I wanted to get things going while I have time and motivation (that last part is important haha). 

If I did something in an ugly way please tell me as well. I still had to use  `return new Promise((resolve, reject) => {})` at some point, not sure if that's how you're supposed to do it.
I tried to do it the way you did it, but that won't work `observeSocket.connect()` runs asynchronously, thus `load` will return before that promise inside connect is resolved with return.

By types you mean that people that use TypeScript have types to use this library right? That would be an awesome addition.

There's one thing that come to mind about the TypeScript rewrite yesterday, won't that make the project harder to work on for other people? A lot more people know JavaScript, not everybody knows TypeScript. Or do you think it won't make much of a difference?

I also wanted to add unit tests at some point (was thinking about using AVA https://github.com/avajs/ava), not sure how TypeScript will affect that.

As for your two questions in ipcInterface.js, I don't know where the message comes from either.... . Deleting it right after you send the message will probably break the module. Take a look at `_events.js` for the ipcInterface at the bottom of the file. That's where the promises are resolved or rejected and where it is deleted from the the `ipcRequests` objects. That part was a real headache to write, and I agree it's hard to read and hard to understand. But it ensures, that the responses from **mpv** can be matched with the sent messages.

**Comment by AxelTerizaki** [comment] 2020-03-27 14:46
- Yes, you're absolutely right about `observeSocket.connect()`. In this cas use of `return new Promise` is alas mandatory. I'll rewrite that part later. I'll also take a look at what you did, but I had enough coding for the day, haha :)
- Speaking of async/await I recommend the use of [execa](https://github.com/sindresorhus/execa) to replace child_process, as it works well with promises and has a few extra, welcome features when dealing with multi-platform binaries (namely how options are passed and all that)
- The `package.json` the `types` field is read by typescript so it can know where to find your moduyles's types, so people using typescript and node-mpv can know which types to use. That's where you declare options/arguments when they are objects (so your user's editor knows what's available or not). Right now it points to the wrong file but I'll fix that later. If you'd like, I can focus on just that right now, and let you handle the async/await rewrite. We can certainly do the typescript rewrite another time : just adding types to the module could be enough for now (as long as they're consistent with reality : one advantage of the moduele's code and the caller app's code sharing the same types is that you're pretty sure they're consistent. During KM's developmetn with typescript I ran with a very few rare issues, like with `passport` which we use for auth'ing users, which wasn't exactly equal to reality in the code.)
- Adding typescript obviously adds a layer of didficulty, but to me it's a bit less complicated than babel, for example. Also, since I added typescript and ts-node to dev dependencies, a new dev doing a npm install will have no issues as everything will be available, and if he has the right IDE plugins like ESlint and typescript enabled, then it'll work just fine. What's important with TS is that it uses the more modern ES way of things when it comes to writing javascript. The only typescript-only additions come from type declarations, the rest is ES6+ javascript, so as long as you know what is async/await or arrow functions, it should be fune, I think.
- For unit tests, I'd recommend doing it in the end once everything is stabilized. We use mocha for Karaoke Mugen.
- Gotcha for the two answers.

I'll merge your work and resume working on that tomorrow, once I find a way to make sure all modules can be inherited in the main mpv class. If not I'll think of some other way. I understand why you did it and it's actually clever. but it might be confusing for newcomers I think (it took em a while to understand how it worked and built the class object for mpv). If I don't find a way to do it a bit simpler, I'll just revert and go back to how you did it :)

**Comment by AxelTerizaki** [comment] 2020-03-27 15:08
Okay so, my issue with the module definition in mpv.js has two solutions :

# The subobject way

So basically the `audio` submodule would be called like that 👍 

```JS
import audioModule from './_audio';

...

export default class mpv {
...
   audio = audioModule
... 
}
```
The downside is that people will have to rewrite their code and use 
```
const myMpv = new mpv()
myMpv.audio.addAudioTrack()
```

# The explicit way

```
import audioModule from './_audio';

...

export default class mpv {
...
   addAudioTrack = audioModule.addAudioTrack
   removeAudioTrack = audioModule.removeAudioTrack
... 
}
```

Since we're doing a v3 of the module, it can still be worth it to rewrite stuff the first way.

It's up to you though :) Not sure if there are other ways like that, to make it cleaner.

I'll comment again if I find other solutions.

**Comment by AxelTerizaki** [comment] 2020-03-27 15:11
Apparently I could also use module augmentation, see https://www.typescriptlang.org/docs/handbook/declaration-merging.html

That could be ideal, actually.

**Comment by j-holub** [comment] 2020-03-27 16:04
> Since we're doing a v3 of the module, it can still be worth it to rewrite stuff the first way.

Version 2 isn't even done yet. I thought this was just an internal rewrite, that wouldn't change anything for the people using it. Shipping Version 2 is for sure my priority so far.

I mean I have actually done a project in TypeScript myself in the past, it was a very small one pag webapp, nothing special, so I have some experiences defining types and stuff, it's just been a while.

I mean at the moment you don't need babel, you don't need any IDE, you pretty much need nothing. I mean obviously once npm installed everything the compilers will be there and stuff, but still I would assume it makes writing pull requests for other people a lot harder, as testing the code becomes more difficult if you've neber used TypeScript before.

Model Augmentation looks super bloated but I see where you're coming from, it could make everything more structured and easier to read.

I'm still on the fence about this, even the small changes you made, made everything more bloated and a lot harder to understand and adds weird files like `.eslintrc.json`, which to me doesn't look like it should be committed to the repository, because that depends on the person writing the code, or am I wrong?

How can I commit stuff to your TypeScript rewrite if we really pull this through? Because if you rewrite the whole code in TypeScript I won't be able to do anything anymore with this module, because I won't understand anything :D

**Comment by AxelTerizaki** [comment] 2020-03-28 10:10
I meant version 2, not 3, my bad.

Module Augmentation was just an idea, I'm not even sure if it wouldn't be a bit too complicated for our usecase. After thinking about it more and more, I think he first solution I highlighted with submodules having their own objects would be better, but it will involve a harder migration from people coming from v1. 

`.eslintrc.json` isn't weird, it allows people who dev for the module to share the same kind of rules and make sure everyone is writing the same kind of code. Obviously you can put it inside .npmignore to avoid shipping it with the module.

For committing stuff I'll need to wokr out how permissions work on github to add you to the repo haha. I'm used to gitlab permissions so I'll have to look around a bit, give me a few. And you're right, if we rewrite everything in typescript now, it's going to be like you won't be able to do a thing to it anymore, sort of. So it's your call ultimately, i just wanted to show what was possible, or how we could achieve this.

I think that, to close this issue, we only need to write a types definition and include it in the repo. If you'd like it better, I can focus on that and discard the current branch.

**Comment by j-holub** [comment] 2020-05-15 19:08
Since I released Node-MPV 2 as beta, how should we proceed with this?

**Comment by AxelTerizaki** [comment] 2020-05-15 19:22
I suppose we should just write types along with the standard JS code.

I admit I haven't looked into this in a while though :)

**Closed as completed** 2020-07-10 09:34 UTC
